In [1]:
from data_utils import *
from evaluate import *
from dataset import TLDataset
from transformers import T5ForConditionalGeneration,AutoTokenizer, AutoConfig
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl
import argparse
import logging
import torch
from multiprocessing import cpu_count
from finetuner import T5FineTuner
from ray_lightning import RayStrategy
from pytorch_lightning.callbacks.early_stopping import EarlyStopping
from pytorch_lightning.callbacks import ModelCheckpoint
from tqdm import tqdm
from pytorch_lightning import loggers as pl_loggers
import ray
import ast
import os
import gc
from data_utils import *
from evaluate import *


output_path_dir = "/home/salzubi_umass_edu/experiments/"
train_bsz = 8
lr = 3e-4
train_fraction = 1
model_name = "google/flan-t5-base"
num_gpus = torch.cuda.device_count()
num_cpus = cpu_count()

args_dict = dict(
    # file_name = file_name,
    # output_dir=output_path_dir, # path to save the checkpoints
    model_name_or_path=model_name,
    tokenizer_name_or_path=model_name,
    max_seq_length=512,
    train_fraction= train_fraction,
    lr=lr,
    weight_decay=0.0,
    scheduler_factor = .1,
    use_gpu = True if num_gpus > 0 else False,
    train_batch_size=train_bsz,
    eval_batch_size=32,
    num_train_steps=10000000,
    es_patience = 4,
    val_check_interval = .25,
    dropout = .2,
    n_gpu=num_gpus,
    cpu_per_device=num_cpus,
    task = "classification",
)

args = argparse.Namespace(**args_dict)
tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path)

/work/salzubi_umass_edu/.conda/envs/wmt_env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-06-15 08:44:22.972391: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-15 08:44:23.132313: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-15 08:44:24.403810: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-06-15 08:44:24.403903: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-06-15 08:44:24.403912: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

In [2]:
model = load_ckpt(args, "../experiments/all_src_tasks_TL.ckpt")

In [3]:
test = pd.read_csv("../experiments/multipit_tests/processed_multipit_train_unlabeled.csv")
test_data = TLDataset(test[:3000], tokenizer)
test_loader = DataLoader(test_data, batch_size=15, shuffle=False, num_workers=16, drop_last=False)

In [4]:
evaluated_batch, scores = evaluate_batch(test_loader, model, tokenizer, output_scores=True)

200it [01:32,  2.17it/s]

In [37]:
final_scores = torch.vstack(scores).view(3000, 8,-1)

In [38]:
softmax = torch.nn.Softmax(-1)
# label2id = {5: 305, 4: 314, 1: 209, 3: 220, 2: 204}
label2id = {"True": 10988, "False": 10747}

id2label = {v:k for k,v in label2id.items()}
stacked_scores = torch.vstack(scores)

In [46]:
best_scores = {'example': [], "label": [],'score': []}
for i in range(len(final_scores)):
    curr_sentence = final_scores[i, :, :]
    score_1 = torch.max(softmax(curr_sentence)).item()
    label_1 = tokenizer.decode(torch.argmax(softmax(curr_sentence),axis=-1))
    
    best_scores['example'] += [str(i)]    
    best_scores['label'] += [str(label_1)]
    best_scores['score'] += [str(score_1)]
    
best_df = pd.DataFrame(best_scores)

In [48]:
best_df.sort_values(by=['score'])

     example                      label                score
2792    2792   3.73.74.02.71.04.04.04.5  0.28174054622650146
2762    2762   3.51.04.03.75.03.51.03.5  0.28922802209854126
1217    1217   3.73.71.03.54.04.03.73.5  0.30702266097068787
1187    1187   3.72.74.04.04.04.03.54.0   0.3267618417739868
137      137   1.01.04.55.04.03.51.01.0   0.3294786214828491
...      ...                        ...                  ...
2048    2048  neutral neutral04  040452                  1.0
2049    2049            neutral6363 31                   1.0
2050    2050         neutral63  636331                   1.0
623      623          neutral0452  52                    1.0
2093    2093   neutral0404 neutral52                     1.0

[3000 rows x 3 columns]

In [15]:
stacked_scores.shape

torch.Size([23252, 32128])

In [8]:
torch.argmax(softmax(stacked_scores[5][1]))

tensor(0)

In [9]:
tokenizer.decode(3891)

'63'

In [19]:
# # real_output = {'example': [], '1': [], '2': [], '3': [], '4': [], '5': []}
# best_scores = {'example': [], 'score': []} #'label': []
# for idx, (score1, score2) in enumerate(scores):
#     if idx % 2 == 0:
#         norm_score1 = softmax(score1)
#         norm_score2 = softmax(score2)
#         real_output['example'] += [str(idx)]
#         real_output['example'] += [str(idx+1)]
#         best_scores['example'] += [str(idx)]
#         best_scores['example'] += [str(idx+1)]
        
#         best_score_token1 = torch.argmax(norm_score1).item()
#         best_score_token2 = torch.argmax(norm_score2).item()
        
#         best_score1 = norm_score1[best_score_token1].item()
#         best_score2 = norm_score2[best_score_token2].item()
        
#         # best_label1 = id2label[best_score_token1]
#         # best_label2 = id2label[best_score_token2]
        
#         # best_scores['label'] += [str(best_label1)]
#         # best_scores['label'] += [str(best_label2)]
#         best_scores['score'] += [str(best_score1)]
#         best_scores['score'] += [str(best_score2)]        

        
#         # for label, token_id in label2id.items():
#         #     real_output[str(label)] += [norm_score1[token_id].item()]
#         #     real_output[str(label)] += [norm_score2[token_id].item()]

#         #     # print(norm_score1[token_id], norm_score2[token_id])
#         # print()
#         # print()
        
# best_df = pd.DataFrame(best_scores)
# # real_df = pd.DataFrame(real_output)

In [23]:
least_confident_examples = best_df.sort_values(by = ["score"])

In [24]:
least_confident_examples.to_csv("../experiments/multipit_tests/least_confident_train_logits.csv")

In [32]:
least_confident_examples

      example                 score
2073     2073   0.04994606599211693
7438     7438  0.059168312698602676
10521   10521  0.061195552349090576
5305     5305   0.06810060143470764
5448     5448   0.06950264424085617
...       ...                   ...
3927     3927                   1.0
3939     3939                   1.0
3947     3947                   1.0
3871     3871                   1.0
4070     4070                   1.0

[11624 rows x 2 columns]

In [25]:
df1 = pd.read_csv("../experiments/multipit_tests/processed_multipit_train_k=100.csv")
all_train = pd.read_csv("../experiments/multipit_tests/processed_multipit_train_unlabeled.csv")

In [30]:
all_train[all_train.index.isin(least_confident_examples[:500].index)]

,Unnamed: 0.1,Unnamed: 0,input_text,labels,prefix,dataset,dataset_type,task_id
38,38,711928,Is sentence2 a paraphrase of sentence1? Answer...,True,binary classification,multipit,TRG,44
50,50,626202,Is sentence2 a paraphrase of sentence1? Answer...,False,binary classification,multipit,TRG,44
167,167,42833,Is sentence2 a paraphrase of sentence1? Answer...,True,binary classification,multipit,TRG,44
183,183,78156,Is sentence2 a paraphrase of sentence1? Answer...,True,binary classification,multipit,TRG,44
189,189,59320,Is sentence2 a paraphrase of sentence1? Answer...,False,binary classification,multipit,TRG,44
...,...,...,...,...,...,...,...,...
3609,3609,170813,Is sentence2 a paraphrase of sentence1? Answer...,True,binary classification,multipit,TRG,44
3663,3663,408446,Is sentence2 a paraphrase of sentence1? Answer...,False,binary classification,multipit,TRG,44
3678,3678,304154,Is sentence2 a paraphrase of sentence1? Answer...,True,binary classification,multipit,TRG,44
3682,3682,9192,Is sentence2 a paraphrase of sentence1? Answer...,False,binary classification,multipit,TRG,44
3686,3686,824164,Is sentence2 a paraphrase of sentence1? Answer...,False,binary classification,multipit,TRG,44

In [ ]:
train_200 = all_train.sample(100)
train_500 = all_train.sample(400)

In [ ]:
pd.concat([train_200, df1]).to_csv("processed_multipit_train_k=200.csv")

In [ ]:
pd.concat([train_500, df1]).to_csv("processed_multipit_train_k=500.csv")